name: Tag
description: >-
  This is a GitHub action that composes a Git tag that's composed of the version
  extracted from the `.version` file and the `asmttpd` version extracted from
  the `Dockerfile`.

runs:
  using: composite
  steps:
    - name: tag
      id: tag
      shell: bash
      run: >-
        ${{ github.action_path }}/scripts/version.sh

outputs:
  asmttpd_version:
    description: Asmttpd version.
    value: ${{ steps.tag.outputs.asmttpd_version }}
  file_version:
    description: File version.
    value: ${{ steps.tag.outputs.file_version }}
  docker_tag:
    description: Docker tag.
    value: ${{ steps.tag.outputs.docker_tag }}
  git_tag:
    description: Git Tag.
    value: ${{ steps.tag.outputs.git_tag }}
